# Generated by Django 6.0.3 on 2026-05-14 15:50

import django.db.models.deletion
import uuid
import wallpapers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('thumbnail_url', models.URLField(blank=True, default='', max_length=512)),
                ('wallpaper_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Wallpaper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('cloudinary_id', models.CharField(max_length=255, unique=True)),
                ('secure_url', models.URLField(max_length=512)),
                ('thumbnail_url', models.URLField(max_length=512)),
                ('tags', wallpapers.models.TagField(blank=True, default='', max_length=1000)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('format', models.CharField(blank=True, default='', max_length=10)),
                ('dominant_color', models.CharField(blank=True, default='', max_length=7)),
                ('downloads', models.BigIntegerField(default=0)),
                ('views', models.BigIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_hash', models.CharField(blank=True, default='', max_length=64)),
                ('referrer', models.URLField(blank=True, default='', max_length=512)),
                ('wallpaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_records', to='wallpapers.wallpaper')),
            ],
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('wallpaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_records', to='wallpapers.wallpaper')),
            ],
        ),
        migrations.AddIndex(
            model_name='wallpaper',
            index=models.Index(fields=['category'], name='idx_wallpapers_category'),
        ),
        migrations.AddIndex(
            model_name='wallpaper',
            index=models.Index(fields=['-created_at'], name='idx_wallpapers_created'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['wallpaper'], name='wallpapers__wallpap_89ccb3_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['-viewed_at'], name='wallpapers__viewed__377a54_idx'),
        ),
        migrations.AddIndex(
            model_name='download',
            index=models.Index(fields=['wallpaper'], name='wallpapers__wallpap_5560ad_idx'),
        ),
        migrations.AddIndex(
            model_name='download',
            index=models.Index(fields=['-downloaded_at'], name='wallpapers__downloa_6e611f_idx'),
        ),
    ]
