# Generated by Django 6.0.3 on 2026-05-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpapers', '0002_siteconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='sha256',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
